baseURL = "https://pandaoyabun.github.io/daily_blog/"
canonifyURLs = true
relativeURLs = true
languageCode = "ja-jp"
title = "ãŠã‚„ã¶ã‚“ã®ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–"
theme = 'hugo-theme-stack'

removePathAccents = true
summaryLength = 10

# HTMLã‚¿ã‚°ï¼ˆã‚¢ãƒ¡ãƒ–ãƒ­ã®è¡¨ã‚„ãƒªãƒ³ã‚¯ï¼‰ã‚’è¨±å¯ã™ã‚‹
[markup.goldmark.renderer]
    unsafe = true

[params]
    mainSections = ["post"]

    [params.sidebar]
        enabled = true
        [params.sidebar.avatar]
            enabled = true
            # URLã‚’ç›´æ¥æ›¸ãå ´åˆã¯ 'local = false' ã‚’æ˜ç¤ºã—ã¾ã™
            local = false
            src = "https://github.com/github.png"
        
        emoji = "ğŸš€"
        subtitle = "20å¹´åˆ†ã®è¨˜éŒ²ã‚’å¥ªé‚„ä¸­"

    [params.article]
        [params.article.license]
            enabled = false

    [params.footer]
        enabled = true